org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC
kotlin.mpp.enableCInteropCommonization=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false
kotlin.native.ignoreDisabledTargets=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL
org.gradle.configuration-cache=false
